### ISSUE TITLE
[Deployment]: Deploy the frontend

### ISSUE THREAD

**Issue by andreu-vall** [UB-ES-2023-A2/kasula-frontend#74]

**Comment by andreu-vall** [comment]
For the sprint 1 we'll also need the frontend deployed

**Comment by BlessedLongsword** [comment]
Is this considered FE because of potential modification of the FE repository, mainly Dockerfiles and such?

**Comment by andreu-vall** [comment]
Yes, I have split the task in Devops, Backend and Frontend
